language: ruby
rvm:
  - 2.1.5

before_install:
  - export NOKOGIRI_USE_SYSTEM_LIBRARIES=true

install:
  - travis_retry gem install github-pages
  - travis_retry npm install -g grunt-cli
  - travis_retry npm install

script:
  - grunt build

branches:
  only:
  - master
  - gh-pages

notifications:
  email: false

sudo: false